### PR TITLE
Build pull requests

### LINKED ISSUE #10: Handle pull requests
When running a build for a pull request:
1. Use the staging content service URL.
2. Issue a new staging content service API key.
3. Inject a revision ID based on the git commit SHA, like `/build-12341234/`, to the content ID base.
4. Run preparers normally.
5. Revoke the staging API key.

### PR DESCRIPTION
**Pull request by smashwilson**
Submit pull request content to the staging content service API with a unique-ish revision ID. On completion, comment on the originating pull request with a link to the built content.

Fixes #10.

### CODE REVIEW

**Comment by smashwilson** [comment]
For reference: the [GitHub API documentation](https://developer.github.com/v3/issues/comments/#create-a-comment) for pull request comments.

**Comment by smashwilson** [comment]
The first successful pull request build published to staging: :rocket: 

screen shot 2016-03-10 at 10 04 27 am

**Comment by ktbartholomew** [comment]
The best part of this is getting to read your internal dialogue

**Comment by smashwilson** [comment]
It [works](https://github.com/deconst/deconst-docs/pull/225#issuecomment-195483939) in the simple case! I'm guessing that we'll hit more edge cases once we run builds with multiple content roots and so on.

Unfortunately it's not easy to set up testing for Strider plugins without a ton of mocking that I didn't feel like doing just yet, so we'll have to test the YOLO way - in production. I'll fix stack traces as they happen.

**Pull request merged**
